version: '3.4'

services:

  mongo-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: tegmob

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      -  "50080:80"
      -  "50443:443"
    depends_on:
      -  mongo-db