service: tegmob-backend-match

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

  environment:
    DYNAMODB_MATCH_TABLE: ${self:service}-match-${opt:stage}
    TEGMOB_PLAYER_API: "https://fjskeqpwi3.execute-api.us-east-1.amazonaws.com/dev/player"

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan*
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:service}-match-${opt:stage}


plugins:
  - serverless-pseudo-parameters

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: match
          method: post
  join:
    handler: handler.join
    events:
      - http:
          path: match/join/{name}
          method: put
  leave:
    handler: handler.leave
    events:
      - http:
          path: match/leave/{name}
          method: put
  delete:
    handler: handler.delete
    events:
      - http:
          path: match/{name}
          method: delete
  get:
    handler: handler.get
    events:
      - http:
          path: match/{name}
          method: get
  list:
    handler: handler.list
    events:
      - http:
          path: match
          method: get

resources:
  Resources:
    matchTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-match-${opt:stage}
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
