########## -- USERS API
POST https://tzdb0jz1yh.execute-api.us-east-1.amazonaws.com/dev/users HTTP/1.1
content-type: application/json

{
    "username": "test",
    "password": "test",
    "firstname": "test",
    "lastname": "test"
}
####
PUT https://tzdb0jz1yh.execute-api.us-east-1.amazonaws.com/dev/users/test HTTP/1.1
content-type: application/json

{
    "firstname": "test",
    "lastname": "cambiada",
    "password": "cambiada"
}
####
DELETE https://tzdb0jz1yh.execute-api.us-east-1.amazonaws.com/dev/users/test HTTP/1.1
####
GET https://tzdb0jz1yh.execute-api.us-east-1.amazonaws.com/dev/users/test HTTP/1.1
####
GET https://tzdb0jz1yh.execute-api.us-east-1.amazonaws.com/dev/users HTTP/1.1

########## -- PLAYERS API
POST https://fjskeqpwi3.execute-api.us-east-1.amazonaws.com/dev/player/partido1 HTTP/1.1
content-type: application/json

{
    "userid": "test"
}
####
DELETE https://fjskeqpwi3.execute-api.us-east-1.amazonaws.com/dev/player/partido1 HTTP/1.1
####
DELETE https://fjskeqpwi3.execute-api.us-east-1.amazonaws.com/dev/player HTTP/1.1
content-type: application/json

{
    "matchid": "partido1"
}
####
GET https://fjskeqpwi3.execute-api.us-east-1.amazonaws.com/dev/player HTTP/1.1


########## -- MATCH API
POST https://e9c4x73vla.execute-api.us-east-1.amazonaws.com/dev/match HTTP/1.1
content-type: application/json

{
    "name": "partido1",
    "owner": "test",
    "size": "4"
}
####
PUT https://e9c4x73vla.execute-api.us-east-1.amazonaws.com/dev/match/join/partido1 HTTP/1.1
content-type: application/json

{
    "userToAdd": "test"
}
####
PUT https://e9c4x73vla.execute-api.us-east-1.amazonaws.com/dev/match/leave/partido1 HTTP/1.1
content-type: application/json

{
    "userToRemove": "test"
}
####
DELETE https://e9c4x73vla.execute-api.us-east-1.amazonaws.com/dev/match/partido1 HTTP/1.1
content-type: application/json

{
    "username": "test",
    "password": "test",
    "firstname": "test",
    "lastname": "test"
}
####
GET https://e9c4x73vla.execute-api.us-east-1.amazonaws.com/dev/match/partido1 HTTP/1.1
####
GET https://e9c4x73vla.execute-api.us-east-1.amazonaws.com/dev/match HTTP/1.1
####